
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/programs/i386-mac/system/sbgrid_bin/"
      - "/opt/homebrew/bin/"
      - "/opt/anaconda3/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/Little Snitch.app/Contents/Components/"
      - "/Users/roshanpathak/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
      - "/programs/share/bin/"
      - "/programs/share/sbgrid/bin/"
      - "/programs/i386-mac/sbgrid_installer/latest/"
      - "/usr/X11/bin/"
    searched_directories:
      - "/programs/i386-mac/system/sbgrid_bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/anaconda3/bin/uname"
      - "/opt/anaconda3/condabin/uname"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/programs/i386-mac/system/sbgrid_bin"
        - "/opt/homebrew/bin"
        - "/opt/anaconda3/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/Little Snitch.app/Contents/Components"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/roshanpathak/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/programs/share/bin"
        - "/programs/share/sbgrid/bin"
        - "/programs/i386-mac/sbgrid_installer/latest"
        - "/opt/X11/bin"
        - "/usr/X11/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.0.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/programs/i386-mac/system/sbgrid_bin/"
      - "/opt/homebrew/bin/"
      - "/opt/anaconda3/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/Little Snitch.app/Contents/Components/"
      - "/Users/roshanpathak/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts/"
      - "/programs/share/bin/"
      - "/programs/share/sbgrid/bin/"
      - "/programs/i386-mac/sbgrid_installer/latest/"
      - "/usr/X11/bin/"
    searched_directories:
      - "/programs/i386-mac/system/sbgrid_bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
    found: "/opt/anaconda3/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/programs/i386-mac/system/sbgrid_bin"
        - "/opt/homebrew/bin"
        - "/opt/anaconda3/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/Little Snitch.app/Contents/Components"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/roshanpathak/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/roshanpathak/.vscode/extensions/ms-python.debugpy-2025.18.0-darwin-arm64/bundled/scripts/noConfigScripts"
        - "/programs/share/bin"
        - "/programs/share/sbgrid/bin"
        - "/programs/i386-mac/sbgrid_installer/latest"
        - "/opt/X11/bin"
        - "/usr/X11/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
